### ISSUE TITLE
error: conflicting types for 'getline' on Mac OSX

### ISSUE THREAD

**Issue by luisdaher** [mad4j/Super-Star-Trek#1]
Hi! I hope that this message finds you well :)

I've tried to compile the game using a Mac device, and I got this error:

```
startrek.c:1845:1: error: conflicting types for 'getline'
getline(char *s)
^
/usr/include/stdio.h:359:9: note: previous declaration is here
ssize_t getline(char ** __restrict __linep, size_t * __restrict __linecapp, FILE * __restrict __stream) __OSX_AVAILABLE_STARTING(__MAC_10_7, __IPHONE_4_3);
```

By replacing `getline()` occurrences with `getLine()`, it compiled smoothly, as it stopped conflicting with an existing `stdio.h` function name. 

Anyway, just my two cents to increase compatibility. I hope that helps :D

Cheers 🖖

**Comment by mad4j** [comment]
Thanks for your contribution.
Resolved few compliace issue with modern GCC. Now it should compile without errors or warnings.

Regards,
Daniele
